# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importing.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(579, 188)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_1.addWidget(self.label)
        self.apiKey = QtWidgets.QLineEdit(Dialog)
        self.apiKey.setToolTip("")
        self.apiKey.setWhatsThis("")
        self.apiKey.setInputMask("")
        self.apiKey.setObjectName("apiKey")
        self.horizontalLayout_1.addWidget(self.apiKey)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.baseKey = QtWidgets.QLineEdit(Dialog)
        self.baseKey.setText("")
        self.baseKey.setObjectName("baseKey")
        self.horizontalLayout_2.addWidget(self.baseKey)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.csvPath = QtWidgets.QLineEdit(Dialog)
        self.csvPath.setObjectName("csvPath")
        self.horizontalLayout_4.addWidget(self.csvPath)
        self.openBtn = QtWidgets.QPushButton(Dialog)
        self.openBtn.setObjectName("openBtn")
        self.horizontalLayout_4.addWidget(self.openBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.tableName = QtWidgets.QLineEdit(Dialog)
        self.tableName.setObjectName("tableName")
        self.horizontalLayout_6.addWidget(self.tableName)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.viewName = QtWidgets.QLineEdit(Dialog)
        self.viewName.setObjectName("viewName")
        self.horizontalLayout_7.addWidget(self.viewName)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.imgHeight = QtWidgets.QSpinBox(Dialog)
        self.imgHeight.setMinimumSize(QtCore.QSize(0, 0))
        self.imgHeight.setMaximum(512)
        self.imgHeight.setSingleStep(2)
        self.imgHeight.setObjectName("imgHeight")
        self.horizontalLayout_8.addWidget(self.imgHeight)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.modelArea = QtWidgets.QWidget(Dialog)
        self.modelArea.setMinimumSize(QtCore.QSize(100, 0))
        self.modelArea.setObjectName("modelArea")
        self.horizontalLayout.addWidget(self.modelArea)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.importBtn = QtWidgets.QPushButton(Dialog)
        self.importBtn.setObjectName("importBtn")
        self.horizontalLayout_3.addWidget(self.importBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        self.importBtn.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Import from Airtable"))
        self.label.setText(_translate("Dialog", "Airtable API key (<a href=\"https://airtable.com/account\">https://airtable.com/account</a>):"))
        self.apiKey.setPlaceholderText(_translate("Dialog", "keyrhbKBk6UQfNTPP"))
        self.label_2.setText(_translate("Dialog", "Base API key (<a href=\"https://airtable.com/api\">https://airtable.com/api</a>):"))
        self.baseKey.setPlaceholderText(_translate("Dialog", "appHjRH699hyH52Kt"))
        self.label_4.setText(_translate("Dialog", "Path to the CSV file:"))
        self.csvPath.setPlaceholderText(_translate("Dialog", "C:\\Users\\Admin\\Downloads\\Books-Grid view.csv"))
        self.openBtn.setText(_translate("Dialog", "Open"))
        self.label_3.setText(_translate("Dialog", "Table Name:"))
        self.tableName.setPlaceholderText(_translate("Dialog", "Books"))
        self.label_5.setText(_translate("Dialog", "View Name:"))
        self.viewName.setPlaceholderText(_translate("Dialog", "Grid view"))
        self.label_6.setText(_translate("Dialog", "Picture Height:"))
        self.label_7.setText(_translate("Dialog", "px"))
        self.label_8.setText(_translate("Dialog", "Note Type: "))
        self.importBtn.setText(_translate("Dialog", "Import"))

