name: checks
 
on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
         submodules: recursive

      - name: Install npm dependencies
        run: npm ci

      - name: Run standard
        run: npx standard

      - name: Install Python dependencies
        run: python -m pip install aqt pyqt5-stubs mypy

      - name: Run mypy
        run: python -m mypy --no-strict-optional --disallow-untyped-defs .
