name: checks

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install npm dependencies
        run: npm ci

      - name: Run standard
        run: npx standard

      - name: Install Python dependencies
        run: python -m pip install aqt mypy pyqt5-stubs pyqt6-stubs types-simplejson

      - name: Run mypy
        run: python -m mypy .
