name: checks
 
on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
         submodules: recursive
      
      - name: Install dependencies
        run: python -m pip install aqt pyqt5-stubs mypy

      - name: Run mypy
        run: python -m mypy --no-strict-optional --disallow-untyped-defs .
